package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 03 12:27:17 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjImpl() {
    }
}

